package ShapePlusPlus.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Color_Constraints extends BaseConstraintsDescriptor {
  public Color_Constraints() {
    super(CONCEPTS.Color$Yy);
  }

  public static class Red_Property extends BasePropertyConstraintsDescriptor {
    public Red_Property(ConstraintsDescriptor container) {
      super(PROPS.red$PFdp, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:bd2d20e8-94b3-4c45-aa97-838277808038(ShapePlusPlus.constraints)", "5884675094284466488"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 0 && propertyValue <= 255;
    }
  }
  public static class Green_Property extends BasePropertyConstraintsDescriptor {
    public Green_Property(ConstraintsDescriptor container) {
      super(PROPS.green$PKAK, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:bd2d20e8-94b3-4c45-aa97-838277808038(ShapePlusPlus.constraints)", "5884675094284577016"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 0 && propertyValue <= 255;
    }
  }
  public static class Blue_Property extends BasePropertyConstraintsDescriptor {
    public Blue_Property(ConstraintsDescriptor container) {
      super(PROPS.blue$PLLP, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:bd2d20e8-94b3-4c45-aa97-838277808038(ShapePlusPlus.constraints)", "5884675094284577167"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 0 && propertyValue <= 255;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.red$PFdp, new Red_Property(this));
    properties.put(PROPS.green$PKAK, new Green_Property(this));
    properties.put(PROPS.blue$PLLP, new Blue_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Color$Yy = MetaAdapterFactory.getConcept(0x9710ea29960d4c8dL, 0xbfcbd895aec7ff5bL, 0x64516100fd618e0dL, "ShapePlusPlus.structure.Color");
  }

  private static final class PROPS {
    /*package*/ static final SProperty red$PFdp = MetaAdapterFactory.getProperty(0x9710ea29960d4c8dL, 0xbfcbd895aec7ff5bL, 0x64516100fd618e0dL, 0x64516100fd628d26L, "red");
    /*package*/ static final SProperty green$PKAK = MetaAdapterFactory.getProperty(0x9710ea29960d4c8dL, 0xbfcbd895aec7ff5bL, 0x64516100fd618e0dL, 0x64516100fd628d28L, "green");
    /*package*/ static final SProperty blue$PLLP = MetaAdapterFactory.getProperty(0x9710ea29960d4c8dL, 0xbfcbd895aec7ff5bL, 0x64516100fd618e0dL, 0x64516100fd628d2dL, "blue");
  }
}
